import{a as P,S,i as c}from"./assets/vendor-CYg6pwNI.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const $="49169306-de27c58c14ea5b5fada8fc03c",R="https://pixabay.com/api/",m=async(r,o,s)=>{try{return(await P.get(R,{params:{key:$,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:s,page:o}})).data}catch{iziToast.error({message:"An error occurred while fetching images. Please try again later.",position:"topRight"}),console.error(error)}},h=document.querySelector(".gallery"),x=()=>{h.innerHTML=""},f=r=>{const o=r.map(({webformatURL:i,largeImageURL:e,tags:t,likes:n,views:v,comments:w,downloads:q})=>`<a class="gallery-item" href="${e}">
          <div class="photo-card">
            <img src="${i}" alt="${t}" />
            <div class="info">
              <p><b>Likes:</b> ${n}</p>
              <p><b>Views:</b> ${v}</p>
              <p><b>Comments:</b> ${w}</p>
              <p><b>Downloads:</b> ${q}</p>
            </div>
          </div>
        </a>`).join("");h.insertAdjacentHTML("beforeend",o),new S(".gallery a").refresh()},u=document.querySelector(".form"),A=document.querySelector(".form-input"),y=document.querySelector(".loader"),g=document.querySelector(".load-more");let a=1,O="",p=0;const l=15;function b(){y.classList.add("active")}function d(){y.classList.remove("active")}function B(){g.style.display="block"}function L(){g.style.display="none"}u.addEventListener("submit",async r=>{r.preventDefault();const o=A.value.trim();if(!o){c.warning({message:"Please enter a valid search query!",position:"topRight"});return}a=1,x(),b(),L();try{const s=await m(o,a,l),i=s.hits;if(d(),i.length===0){c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),u.reset();return}f(i),u.reset(),p=s.totalHits,p>a*l&&B()}catch(s){d(),c.error({message:"An error occurred while fetching images. Please try again later.",position:"topRight"}),console.error(s)}});g.addEventListener("click",async()=>{a+=1,b();try{const r=Math.ceil(p/l),o=a===r,s=await m(O,a,l);d();const i=s.hits;f(i);const{height:e}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"}),a>=r&&(L(),c.info({message:"We're sorry, but you've reached the end of search results",position:"topRight"}))}catch(r){d(),c.error({message:"An error occurred while loading more images.",position:"topRight"}),console.error(r)}});
//# sourceMappingURL=index.js.map
